---
title: "LLNFData"
output: html_document
---

#Site D
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(plyr)
library(tidyr)
library(tidyverse)
library(caret)
library(dplyr)
library(doBy)
library(data.table)
library(pROC)
## Reading all the temperature files in the Site D folder
files = list.files(path = "C:/Users/Dhwani/Documents/Site F G H/Site D", pattern = "*.csv", full.names = TRUE)

datacsv = ldply(files,read.csv,header= FALSE)
datacsv = datacsv[, !(colnames(datacsv) %in% c("V5","V6","V7","V8"))]
## Removing the duplicates and unwanted rows from the csv file
datacsv = datacsv[(!duplicated(datacsv$V2)  & !grepl("Plot",datacsv$V1) & !grepl("#",datacsv$V1)),]
colnames(datacsv)
## Assigning appropriate headers
names(datacsv)[names(datacsv) == "V1"] <- "Seq"
names(datacsv)[names(datacsv) == "V2"] <- "Date&Time"
names(datacsv)[names(datacsv) == "V3"] <- "Temperature"
names(datacsv)[names(datacsv) == "V4"] <- "Intensity"

options(stringsAsFactors = FALSE)

datacsv$`Date&Time`= as.Date(datacsv$`Date&Time`,format="%m/%d/%Y")

datacsv$Temperature = as.numeric(datacsv$Temperature)

cdata <- summaryBy(Temperature ~ datacsv$`Date&Time`, data=datacsv, FUN=c(min,max,mean),is.na=TRUE)

## loading Intensity Dataset
Data_intensity <- read.csv("C:/Users/Dhwani/Documents/status_intensity_observation_data.csv", header=TRUE)

dint <- data.frame(Data_intensity$Observation_Date,Data_intensity$Site_Name,Data_intensity$Species,Data_intensity$Phenophase_Name,Data_intensity$Intensity_Value)

dint$Data_intensity.Observation_Date <- as.Date(str_sub(dint$Data_intensity.Observation_Date,3))

dintD <- subset(dint,dint$Data_intensity.Site_Name=="Site D")

## Applying inner join to join two data set and result will contain phenophase data and Temperature data both
SiteD <- inner_join(dintD,cdata,by=c("Data_intensity.Observation_Date"="Date&Time") ,copy=FALSE, is.na=TRUE)

str(SiteD$Data_intensity.Observation_Date)

write.csv(SiteD, file = "SiteD.csv")

## Reading the finalized
siteD <- read_csv("siteD.csv")
## Summarize the Dataset
summary(siteD)
## From the summary we can see some mutation needed for pocessing the dataset
siteD <- siteD %>% mutate_if(is.character,as.factor)
siteD$Temperature.mean <- addNA(siteD$Temperature.mean,ifany=TRUE)
summary(siteD)

## Since we are interested in the relationship between temperature and breaking leaf buds, we are assigning 1 to
## those that are having the breaking leave buds phenophase and 0 otherwise
siteD$Data_intensity.Phenophase_Name <- ifelse(siteD$Data_intensity.Phenophase_Name=="Breaking leaf buds","Yes","No")
siteD$Data_intensity.Phenophase_Name <- factor(siteD$Data_intensity.Phenophase_Name)
setnames(siteD, old=c("Data_intensity.Phenophase_Name","Data_intensity.Species","Temperature.mean"), new=c("phenophase", "species","tempmean"))

## Then we are going to divide the dataset to two parts - a training dataset and a test dataset(for validation) 
## and develop a logistics regression model 
## First,we are going to determine our target variable - phenophase

trControl <- trainControl(method = 'cv', savePredictions = TRUE, classProbs = TRUE, summaryFunction = twoClassSummary)
model_type <- 'glm'
model_form <- phenophase ~  species+tempmean
target_var <- 'phenophase'


## we split the dataset as 80% and 20% to two parts - training set and testing set
## We will use the first 80% of the dataset as the training data and the latter 20% of the dataset for validation
set.seed(1)
trainIndex <- createDataPartition(siteD[[target_var]], p = 0.8,list=FALSE)
train_set <- siteD[trainIndex,]
test_set <- siteD[-trainIndex,]


## Now we are going to build a logistic regression model based on the training set
lm_pheno <- train(as.formula(model_form),data=train_set,method=model_type,trControl=trControl)
lm_pheno

## Now we are going to perform the model on the test dataset and see how it works on predicting the phenophase for use
## predicting the actual type
pheno_pred <- lm_pheno %>% predict(newdata=test_set,type='raw')
## predicting the probability
pheno_pred_prob <- lm_pheno%>%predict(newdata=test_set,type='prob')

##Let's have the confusion matrix to see how the model is working
positive_class <- 'Yes'
confusionMatrix(pheno_pred,test_set[[target_var]],positive=positive_class)
##Next, let's try to plot the roc curve to investigate the AUC value
roc(test_set[[target_var]],pheno_pred_prob[,positive_class],plot=TRUE,print.auc=TRUE,legacy.axes=TRUE)

```

#Site A
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(plyr)
library(tidyr)
library(tidyverse)
library(caret)
library(dplyr)
library(doBy)
library(data.table)
library(pROC)


files = list.files(path = "C:/Users/Dhwani/Documents/Site F G H/Site A", pattern = "*.csv", full.names = TRUE)

datacsv = ldply(files,read.csv,header= FALSE)
datacsv = datacsv[, !(colnames(datacsv) %in% c("V5","V6","V7","V8"))]
datacsv = datacsv[(!duplicated(datacsv$V2)  & !grepl("Plot",datacsv$V1) & !grepl("#",datacsv$V1)),]
colnames(datacsv)
names(datacsv)[names(datacsv) == "V1"] <- "Seq"
names(datacsv)[names(datacsv) == "V2"] <- "Date&Time"
names(datacsv)[names(datacsv) == "V3"] <- "Temperature"
names(datacsv)[names(datacsv) == "V4"] <- "Intensity"

options(stringsAsFactors = FALSE)

datacsv$`Date&Time`= as.Date(datacsv$`Date&Time`,format="%m/%d/%Y")

datacsv$Temperature = as.numeric(datacsv$Temperature)

cdata <- summaryBy(Temperature ~ datacsv$`Date&Time`, data=datacsv, FUN=c(min,max,mean),is.na=TRUE)


Data_intensity <- read.csv("C:/Users/Dhwani/Documents/status_intensity_observation_data.csv", header=TRUE)

dint <- data.frame(Data_intensity$Observation_Date,Data_intensity$Site_Name,Data_intensity$Species,Data_intensity$Phenophase_Name,Data_intensity$Intensity_Value)

dint$Data_intensity.Observation_Date <- as.Date(str_sub(dint$Data_intensity.Observation_Date,3))

dintD <- subset(dint,dint$Data_intensity.Site_Name=="Site D")

SiteA <- inner_join(dintD,cdata,by=c("Data_intensity.Observation_Date"="Date&Time") ,copy=FALSE, is.na=TRUE)

str(SiteD$Data_intensity.Observation_Date)

write.csv(SiteD, file = "SiteA.csv")


#Site B


files = list.files(path = "C:/Users/Dhwani/Documents/Site F G H/Site B", pattern = "*.csv", full.names = TRUE)

datacsv = ldply(files,read.csv,header= FALSE)
datacsv = datacsv[, !(colnames(datacsv) %in% c("V5","V6","V7","V8"))]
datacsv = datacsv[(!duplicated(datacsv$V2)  & !grepl("Plot",datacsv$V1) & !grepl("#",datacsv$V1)),]
colnames(datacsv)
names(datacsv)[names(datacsv) == "V1"] <- "Seq"
names(datacsv)[names(datacsv) == "V2"] <- "Date&Time"
names(datacsv)[names(datacsv) == "V3"] <- "Temperature"
names(datacsv)[names(datacsv) == "V4"] <- "Intensity"

options(stringsAsFactors = FALSE)

datacsv$`Date&Time`= as.Date(datacsv$`Date&Time`,format="%m/%d/%Y")

datacsv$Temperature = as.numeric(datacsv$Temperature)

cdata <- summaryBy(Temperature ~ datacsv$`Date&Time`, data=datacsv, FUN=c(min,max,mean),is.na=TRUE)


Data_intensity <- read.csv("C:/Users/Dhwani/Documents/status_intensity_observation_data.csv", header=TRUE)

dint <- data.frame(Data_intensity$Observation_Date,Data_intensity$Site_Name,Data_intensity$Species,Data_intensity$Phenophase_Name,Data_intensity$Intensity_Value)

dint$Data_intensity.Observation_Date <- as.Date(str_sub(dint$Data_intensity.Observation_Date,3))

dintD <- subset(dint,dint$Data_intensity.Site_Name=="Site D")

SiteB <- inner_join(dintD,cdata,by=c("Data_intensity.Observation_Date"="Date&Time") ,copy=FALSE, is.na=TRUE)

str(SiteD$Data_intensity.Observation_Date)

write.csv(SiteD, file = "SiteB.csv")


#Site C


files = list.files(path = "C:/Users/Dhwani/Documents/Site F G H/Site C", pattern = "*.csv", full.names = TRUE)

datacsv = ldply(files,read.csv,header= FALSE)
datacsv = datacsv[, !(colnames(datacsv) %in% c("V5","V6","V7","V8"))]
datacsv = datacsv[(!duplicated(datacsv$V2)  & !grepl("Plot",datacsv$V1) & !grepl("#",datacsv$V1)),]
colnames(datacsv)
names(datacsv)[names(datacsv) == "V1"] <- "Seq"
names(datacsv)[names(datacsv) == "V2"] <- "Date&Time"
names(datacsv)[names(datacsv) == "V3"] <- "Temperature"
names(datacsv)[names(datacsv) == "V4"] <- "Intensity"

options(stringsAsFactors = FALSE)

datacsv$`Date&Time`= as.Date(datacsv$`Date&Time`,format="%m/%d/%Y")

datacsv$Temperature = as.numeric(datacsv$Temperature)

cdata <- summaryBy(Temperature ~ datacsv$`Date&Time`, data=datacsv, FUN=c(min,max,mean),is.na=TRUE)


Data_intensity <- read.csv("C:/Users/Dhwani/Documents/status_intensity_observation_data.csv", header=TRUE)

dint <- data.frame(Data_intensity$Observation_Date,Data_intensity$Site_Name,Data_intensity$Species,Data_intensity$Phenophase_Name,Data_intensity$Intensity_Value)

dint$Data_intensity.Observation_Date <- as.Date(str_sub(dint$Data_intensity.Observation_Date,3))

dintD <- subset(dint,dint$Data_intensity.Site_Name=="Site D")

SiteC <- inner_join(dintD,cdata,by=c("Data_intensity.Observation_Date"="Date&Time") ,copy=FALSE, is.na=TRUE)

str(SiteD$Data_intensity.Observation_Date)

write.csv(SiteC, file = "SiteA.csv")


#Site E


files = list.files(path = "C:/Users/Dhwani/Documents/Site F G H/Site E", pattern = "*.csv", full.names = TRUE)

datacsv = ldply(files,read.csv,header= FALSE)
datacsv = datacsv[, !(colnames(datacsv) %in% c("V5","V6","V7","V8"))]
datacsv = datacsv[(!duplicated(datacsv$V2)  & !grepl("Plot",datacsv$V1) & !grepl("#",datacsv$V1)),]
colnames(datacsv)
names(datacsv)[names(datacsv) == "V1"] <- "Seq"
names(datacsv)[names(datacsv) == "V2"] <- "Date&Time"
names(datacsv)[names(datacsv) == "V3"] <- "Temperature"
names(datacsv)[names(datacsv) == "V4"] <- "Intensity"

options(stringsAsFactors = FALSE)

datacsv$`Date&Time`= as.Date(datacsv$`Date&Time`,format="%m/%d/%Y")

datacsv$Temperature = as.numeric(datacsv$Temperature)

cdata <- summaryBy(Temperature ~ datacsv$`Date&Time`, data=datacsv, FUN=c(min,max,mean),is.na=TRUE)


Data_intensity <- read.csv("C:/Users/Dhwani/Documents/status_intensity_observation_data.csv", header=TRUE)

dint <- data.frame(Data_intensity$Observation_Date,Data_intensity$Site_Name,Data_intensity$Species,Data_intensity$Phenophase_Name,Data_intensity$Intensity_Value)

dint$Data_intensity.Observation_Date <- as.Date(str_sub(dint$Data_intensity.Observation_Date,3))

dintD <- subset(dint,dint$Data_intensity.Site_Name=="Site D")

SiteE <- inner_join(dintD,cdata,by=c("Data_intensity.Observation_Date"="Date&Time") ,copy=FALSE, is.na=TRUE)

str(SiteD$Data_intensity.Observation_Date)

write.csv(SiteE, file = "SiteA.csv")


#Site F


files = list.files(path = "C:/Users/Dhwani/Documents/Site F G H/Site F", pattern = "*.csv", full.names = TRUE)

datacsv = ldply(files,read.csv,header= FALSE)
datacsv = datacsv[, !(colnames(datacsv) %in% c("V5","V6","V7","V8"))]
datacsv = datacsv[(!duplicated(datacsv$V2)  & !grepl("Plot",datacsv$V1) & !grepl("#",datacsv$V1)),]
colnames(datacsv)
names(datacsv)[names(datacsv) == "V1"] <- "Seq"
names(datacsv)[names(datacsv) == "V2"] <- "Date&Time"
names(datacsv)[names(datacsv) == "V3"] <- "Temperature"
names(datacsv)[names(datacsv) == "V4"] <- "Intensity"

options(stringsAsFactors = FALSE)

datacsv$`Date&Time`= as.Date(datacsv$`Date&Time`,format="%m/%d/%Y")

datacsv$Temperature = as.numeric(datacsv$Temperature)

cdata <- summaryBy(Temperature ~ datacsv$`Date&Time`, data=datacsv, FUN=c(min,max,mean),is.na=TRUE)


Data_intensity <- read.csv("C:/Users/Dhwani/Documents/status_intensity_observation_data.csv", header=TRUE)

dint <- data.frame(Data_intensity$Observation_Date,Data_intensity$Site_Name,Data_intensity$Species,Data_intensity$Phenophase_Name,Data_intensity$Intensity_Value)

dint$Data_intensity.Observation_Date <- as.Date(str_sub(dint$Data_intensity.Observation_Date,3))

dintD <- subset(dint,dint$Data_intensity.Site_Name=="Site D")

SiteF <- inner_join(dintD,cdata,by=c("Data_intensity.Observation_Date"="Date&Time") ,copy=FALSE, is.na=TRUE)

str(SiteD$Data_intensity.Observation_Date)

write.csv(SiteF, file = "SiteA.csv")

#Site G


files = list.files(path = "C:/Users/Dhwani/Documents/Site F G H/Site G", pattern = "*.csv", full.names = TRUE)

datacsv = ldply(files,read.csv,header= FALSE)
datacsv = datacsv[, !(colnames(datacsv) %in% c("V5","V6","V7","V8"))]
datacsv = datacsv[(!duplicated(datacsv$V2)  & !grepl("Plot",datacsv$V1) & !grepl("#",datacsv$V1)),]
colnames(datacsv)
names(datacsv)[names(datacsv) == "V1"] <- "Seq"
names(datacsv)[names(datacsv) == "V2"] <- "Date&Time"
names(datacsv)[names(datacsv) == "V3"] <- "Temperature"
names(datacsv)[names(datacsv) == "V4"] <- "Intensity"

options(stringsAsFactors = FALSE)

datacsv$`Date&Time`= as.Date(datacsv$`Date&Time`,format="%m/%d/%Y")

datacsv$Temperature = as.numeric(datacsv$Temperature)

cdata <- summaryBy(Temperature ~ datacsv$`Date&Time`, data=datacsv, FUN=c(min,max,mean),is.na=TRUE)


Data_intensity <- read.csv("C:/Users/Dhwani/Documents/status_intensity_observation_data.csv", header=TRUE)

dint <- data.frame(Data_intensity$Observation_Date,Data_intensity$Site_Name,Data_intensity$Species,Data_intensity$Phenophase_Name,Data_intensity$Intensity_Value)

dint$Data_intensity.Observation_Date <- as.Date(str_sub(dint$Data_intensity.Observation_Date,3))

dintD <- subset(dint,dint$Data_intensity.Site_Name=="Site D")

SiteG <- inner_join(dintD,cdata,by=c("Data_intensity.Observation_Date"="Date&Time") ,copy=FALSE, is.na=TRUE)

str(SiteD$Data_intensity.Observation_Date)

write.csv(SiteD, file = "SiteG.csv")


#Site H


files = list.files(path = "C:/Users/Dhwani/Documents/Site F G H/Site H", pattern = "*.csv", full.names = TRUE)

datacsv = ldply(files,read.csv,header= FALSE)
datacsv = datacsv[, !(colnames(datacsv) %in% c("V5","V6","V7","V8"))]
datacsv = datacsv[(!duplicated(datacsv$V2)  & !grepl("Plot",datacsv$V1) & !grepl("#",datacsv$V1)),]
colnames(datacsv)
names(datacsv)[names(datacsv) == "V1"] <- "Seq"
names(datacsv)[names(datacsv) == "V2"] <- "Date&Time"
names(datacsv)[names(datacsv) == "V3"] <- "Temperature"
names(datacsv)[names(datacsv) == "V4"] <- "Intensity"

options(stringsAsFactors = FALSE)

datacsv$`Date&Time`= as.Date(datacsv$`Date&Time`,format="%m/%d/%Y")

datacsv$Temperature = as.numeric(datacsv$Temperature)

cdata <- summaryBy(Temperature ~ datacsv$`Date&Time`, data=datacsv, FUN=c(min,max,mean),is.na=TRUE)


Data_intensity <- read.csv("C:/Users/Dhwani/Documents/status_intensity_observation_data.csv", header=TRUE)

dint <- data.frame(Data_intensity$Observation_Date,Data_intensity$Site_Name,Data_intensity$Species,Data_intensity$Phenophase_Name,Data_intensity$Intensity_Value)

dint$Data_intensity.Observation_Date <- as.Date(str_sub(dint$Data_intensity.Observation_Date,3))

dintD <- subset(dint,dint$Data_intensity.Site_Name=="Site D")

SiteH <- inner_join(dintD,cdata,by=c("Data_intensity.Observation_Date"="Date&Time") ,copy=FALSE, is.na=TRUE)

str(SiteD$Data_intensity.Observation_Date)

write.csv(SiteD, file = "SiteH.csv")
```

